### ISSUE TITLE
How to plot All Anchor Points

### ISSUE THREAD

**Issue by Yingxiu-Chang** [ai4ce/DeepExplorer#3]
Hi, 
I wanna ask that how did you plot all anchor points in a environment shownas Fig.4A of your paper?
Best wishes
Hugh

**Comment by yuhanghe01** [comment]
Hi, thanks for your interest in our work. To plot each anchor points, you need to get the [x, z] position of the agent at each step during exploration. With the [x, z] position, you can convert it to [px, py] position on the top-down map. You can refer to this function `_draw_point()` ([link](https://github.com/ai4ce/DeepExplorer/blob/main/exploration/explore_MP3D.py#L730)) for more detail.

**Comment by Yingxiu-Chang** [comment]
I get it. Many thanks for your help.
